# coding: utf-8

"""
    Astro Registry API

    Astro Registry API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import re  # noqa: F401
import io
import warnings

from pydantic import validate_arguments, ValidationError
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictStr, conint, conlist, validator

from typing import Optional

from astronomerregistry.models.registry_search import RegistrySearch
from astronomerregistry.models.registry_search_request import RegistrySearchRequest

from astronomerregistry.api_client import ApiClient
from astronomerregistry.api_response import ApiResponse
from astronomerregistry.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class SearchApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    def search(self, org_short_name_id : Annotated[StrictStr, Field(..., description="organization FQN")], body : Annotated[RegistrySearchRequest, Field(..., description="request body for a registry search")], is_certified : Annotated[Optional[StrictBool], Field(description="return only certified providers")] = None, is_featured : Annotated[Optional[StrictBool], Field(description="return only featured providers")] = None, is_global : Annotated[Optional[StrictBool], Field(description="return only global providers")] = None, is_private : Annotated[Optional[StrictBool], Field(description="return only private providers")] = None, is_cloud_ide_compatible : Annotated[Optional[StrictBool], Field(description="return only cloud ide compatible providers")] = None, offset : Annotated[Optional[conint(strict=True, ge=0)], Field(description="offset for pagination")] = None, limit : Annotated[Optional[conint(strict=True, ge=0)], Field(description="limit for pagination")] = None, sorts : Annotated[Optional[conlist(StrictStr)], Field(description="sorting criteria, each criterion should conform to format 'fieldName:asc' or 'fieldName:desc'. Default to searchRank:asc")] = None, **kwargs) -> RegistrySearch:  # noqa: E501
        """Search for a registry object  # noqa: E501

        Search for a registry object  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.search(org_short_name_id, body, is_certified, is_featured, is_global, is_private, is_cloud_ide_compatible, offset, limit, sorts, async_req=True)
        >>> result = thread.get()

        :param org_short_name_id: organization FQN (required)
        :type org_short_name_id: str
        :param body: request body for a registry search (required)
        :type body: RegistrySearchRequest
        :param is_certified: return only certified providers
        :type is_certified: bool
        :param is_featured: return only featured providers
        :type is_featured: bool
        :param is_global: return only global providers
        :type is_global: bool
        :param is_private: return only private providers
        :type is_private: bool
        :param is_cloud_ide_compatible: return only cloud ide compatible providers
        :type is_cloud_ide_compatible: bool
        :param offset: offset for pagination
        :type offset: int
        :param limit: limit for pagination
        :type limit: int
        :param sorts: sorting criteria, each criterion should conform to format 'fieldName:asc' or 'fieldName:desc'. Default to searchRank:asc
        :type sorts: List[str]
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: RegistrySearch
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            raise ValueError("Error! Please call the search_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data")
        return self.search_with_http_info(org_short_name_id, body, is_certified, is_featured, is_global, is_private, is_cloud_ide_compatible, offset, limit, sorts, **kwargs)  # noqa: E501

    @validate_arguments
    def search_with_http_info(self, org_short_name_id : Annotated[StrictStr, Field(..., description="organization FQN")], body : Annotated[RegistrySearchRequest, Field(..., description="request body for a registry search")], is_certified : Annotated[Optional[StrictBool], Field(description="return only certified providers")] = None, is_featured : Annotated[Optional[StrictBool], Field(description="return only featured providers")] = None, is_global : Annotated[Optional[StrictBool], Field(description="return only global providers")] = None, is_private : Annotated[Optional[StrictBool], Field(description="return only private providers")] = None, is_cloud_ide_compatible : Annotated[Optional[StrictBool], Field(description="return only cloud ide compatible providers")] = None, offset : Annotated[Optional[conint(strict=True, ge=0)], Field(description="offset for pagination")] = None, limit : Annotated[Optional[conint(strict=True, ge=0)], Field(description="limit for pagination")] = None, sorts : Annotated[Optional[conlist(StrictStr)], Field(description="sorting criteria, each criterion should conform to format 'fieldName:asc' or 'fieldName:desc'. Default to searchRank:asc")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Search for a registry object  # noqa: E501

        Search for a registry object  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.search_with_http_info(org_short_name_id, body, is_certified, is_featured, is_global, is_private, is_cloud_ide_compatible, offset, limit, sorts, async_req=True)
        >>> result = thread.get()

        :param org_short_name_id: organization FQN (required)
        :type org_short_name_id: str
        :param body: request body for a registry search (required)
        :type body: RegistrySearchRequest
        :param is_certified: return only certified providers
        :type is_certified: bool
        :param is_featured: return only featured providers
        :type is_featured: bool
        :param is_global: return only global providers
        :type is_global: bool
        :param is_private: return only private providers
        :type is_private: bool
        :param is_cloud_ide_compatible: return only cloud ide compatible providers
        :type is_cloud_ide_compatible: bool
        :param offset: offset for pagination
        :type offset: int
        :param limit: limit for pagination
        :type limit: int
        :param sorts: sorting criteria, each criterion should conform to format 'fieldName:asc' or 'fieldName:desc'. Default to searchRank:asc
        :type sorts: List[str]
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the 
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(RegistrySearch, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'org_short_name_id',
            'body',
            'is_certified',
            'is_featured',
            'is_global',
            'is_private',
            'is_cloud_ide_compatible',
            'offset',
            'limit',
            'sorts'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method search" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['org_short_name_id']:
            _path_params['orgShortNameId'] = _params['org_short_name_id']


        # process the query parameters
        _query_params = []
        if _params.get('is_certified') is not None:  # noqa: E501
            _query_params.append(('isCertified', _params['is_certified']))

        if _params.get('is_featured') is not None:  # noqa: E501
            _query_params.append(('isFeatured', _params['is_featured']))

        if _params.get('is_global') is not None:  # noqa: E501
            _query_params.append(('isGlobal', _params['is_global']))

        if _params.get('is_private') is not None:  # noqa: E501
            _query_params.append(('isPrivate', _params['is_private']))

        if _params.get('is_cloud_ide_compatible') is not None:  # noqa: E501
            _query_params.append(('isCloudIDECompatible', _params['is_cloud_ide_compatible']))

        if _params.get('offset') is not None:  # noqa: E501
            _query_params.append(('offset', _params['offset']))

        if _params.get('limit') is not None:  # noqa: E501
            _query_params.append(('limit', _params['limit']))

        if _params.get('sorts') is not None:  # noqa: E501
            _query_params.append(('sorts', _params['sorts']))
            _collection_formats['sorts'] = 'csv'

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['body'] is not None:
            _body_params = _params['body']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "RegistrySearch",
            '401': "Error",
            '403': "Error",
            '500': "Error",
        }

        return self.api_client.call_api(
            '/organizations/{orgShortNameId}/search', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
