# coding: utf-8

"""
    Astro Core API

    Astro Core API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import astronomercoreapi
from astronomercoreapi.models.project_git import ProjectGit  # noqa: E501
from astronomercoreapi.rest import ApiException

class TestProjectGit(unittest.TestCase):
    """ProjectGit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ProjectGit
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectGit`
        """
        model = astronomercoreapi.models.project_git.ProjectGit()  # noqa: E501
        if include_optional :
            return ProjectGit(
                branch = '', 
                dags_path = '', 
                git_vendor_attributes = astronomercoreapi.models.project_git_vendor_attributes.ProjectGitVendorAttributes(
                    azure_dev_ops_organization = '', 
                    azure_dev_ops_project_id = '', ), 
                repo = '', 
                token_set = True, 
                vendor = 'github'
            )
        else :
            return ProjectGit(
        )
        """

    def testProjectGit(self):
        """Test ProjectGit"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
