# coding: utf-8

"""
    Astro Core API

    Astro Core API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import astronomercoreapi
from astronomercoreapi.api.dag_run_api import DagRunApi  # noqa: E501
from astronomercoreapi.rest import ApiException


class TestDagRunApi(unittest.TestCase):
    """DagRunApi unit test stubs"""

    def setUp(self):
        self.api = astronomercoreapi.api.dag_run_api.DagRunApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_clear_dag_run(self):
        """Test case for clear_dag_run

        Clear a dag run  # noqa: E501
        """
        pass

    def test_update_dag_run(self):
        """Test case for update_dag_run

        Set the state of a dag run  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
