# coding: utf-8

"""
    Astro Core API

    Astro Core API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import astronomercoreapi
from astronomercoreapi.models.ctm_generation_decorator import CtmGenerationDecorator  # noqa: E501
from astronomercoreapi.rest import ApiException

class TestCtmGenerationDecorator(unittest.TestCase):
    """CtmGenerationDecorator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CtmGenerationDecorator
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CtmGenerationDecorator`
        """
        model = astronomercoreapi.models.ctm_generation_decorator.CtmGenerationDecorator()  # noqa: E501
        if include_optional :
            return CtmGenerationDecorator(
                decorator_arg_configs = [
                    ''
                    ], 
                decorator_function_params = [
                    ''
                    ], 
                decorator_name = '', 
                function_arg_configs = [
                    ''
                    ], 
                function_code_config = '', 
                imports = [
                    ''
                    ], 
                include_implicit_deps = True, 
                include_task_id_as_decorator_arg = True, 
                include_task_id_as_function_arg = True
            )
        else :
            return CtmGenerationDecorator(
                decorator_name = '',
                function_code_config = '',
        )
        """

    def testCtmGenerationDecorator(self):
        """Test CtmGenerationDecorator"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
