# coding: utf-8

"""
    Astro Core API

    Astro Core API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import astronomercoreapi
from astronomercoreapi.models.dag_tag import DagTag  # noqa: E501
from astronomercoreapi.rest import ApiException

class TestDagTag(unittest.TestCase):
    """DagTag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DagTag
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DagTag`
        """
        model = astronomercoreapi.models.dag_tag.DagTag()  # noqa: E501
        if include_optional :
            return DagTag(
                name = ''
            )
        else :
            return DagTag(
        )
        """

    def testDagTag(self):
        """Test DagTag"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
