# coding: utf-8

"""
    Astro Core API

    Astro Core API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import astronomercoreapi
from astronomercoreapi.models.vr_variable import VRVariable  # noqa: E501
from astronomercoreapi.rest import ApiException

class TestVRVariable(unittest.TestCase):
    """VRVariable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test VRVariable
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VRVariable`
        """
        model = astronomercoreapi.models.vr_variable.VRVariable()  # noqa: E501
        if include_optional :
            return VRVariable(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                created_by_user = astronomercoreapi.models.basic_subject_profile.BasicSubjectProfile(
                    api_token_name = '', 
                    avatar_url = '', 
                    full_name = '', 
                    id = '', 
                    subject_type = 'USER', 
                    username = '', ), 
                is_secret = True, 
                key = '', 
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                updated_by_user = astronomercoreapi.models.basic_subject_profile.BasicSubjectProfile(
                    api_token_name = '', 
                    avatar_url = '', 
                    full_name = '', 
                    id = '', 
                    subject_type = 'USER', 
                    username = '', ), 
                value = ''
            )
        else :
            return VRVariable(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by_user = astronomercoreapi.models.basic_subject_profile.BasicSubjectProfile(
                    api_token_name = '', 
                    avatar_url = '', 
                    full_name = '', 
                    id = '', 
                    subject_type = 'USER', 
                    username = '', ),
                is_secret = True,
                key = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_by_user = astronomercoreapi.models.basic_subject_profile.BasicSubjectProfile(
                    api_token_name = '', 
                    avatar_url = '', 
                    full_name = '', 
                    id = '', 
                    subject_type = 'USER', 
                    username = '', ),
        )
        """

    def testVRVariable(self):
        """Test VRVariable"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
