# coding: utf-8

"""
    Astro Core API

    Astro Core API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import astronomercoreapi
from astronomercoreapi.models.default_args import DefaultArgs  # noqa: E501
from astronomercoreapi.rest import ApiException

class TestDefaultArgs(unittest.TestCase):
    """DefaultArgs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DefaultArgs
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefaultArgs`
        """
        model = astronomercoreapi.models.default_args.DefaultArgs()  # noqa: E501
        if include_optional :
            return DefaultArgs(
                depends_on_past = True, 
                email = [
                    ''
                    ], 
                email_on_failure = True, 
                email_on_retry = True, 
                execution_timeout_seconds = 56, 
                max_retry_delay_seconds = 56, 
                queue = '', 
                retries = 56, 
                retry_delay_seconds = 56, 
                retry_exponential_backoff = True, 
                sla_seconds = 56, 
                task_concurrency = 56, 
                trigger_rule = ''
            )
        else :
            return DefaultArgs(
        )
        """

    def testDefaultArgs(self):
        """Test DefaultArgs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
