# coding: utf-8

"""
    Astro Core API

    Astro Core API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import astronomercoreapi
from astronomercoreapi.models.post_dag_run import PostDagRun  # noqa: E501
from astronomercoreapi.rest import ApiException

class TestPostDagRun(unittest.TestCase):
    """PostDagRun unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PostDagRun
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostDagRun`
        """
        model = astronomercoreapi.models.post_dag_run.PostDagRun()  # noqa: E501
        if include_optional :
            return PostDagRun(
                conf = None, 
                dag_id = '', 
                dag_run_id = '', 
                end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                external_trigger = True, 
                logical_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                state = ''
            )
        else :
            return PostDagRun(
        )
        """

    def testPostDagRun(self):
        """Test PostDagRun"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
