# coding: utf-8

"""
    Astro Core API

    Astro Core API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import astronomercoreapi
from astronomercoreapi.models.instant_metrics_paginated import InstantMetricsPaginated  # noqa: E501
from astronomercoreapi.rest import ApiException

class TestInstantMetricsPaginated(unittest.TestCase):
    """InstantMetricsPaginated unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InstantMetricsPaginated
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InstantMetricsPaginated`
        """
        model = astronomercoreapi.models.instant_metrics_paginated.InstantMetricsPaginated()  # noqa: E501
        if include_optional :
            return InstantMetricsPaginated(
                limit = 56, 
                metrics = [
                    astronomercoreapi.models.instant_metric.InstantMetric(
                        deployment_id = '', 
                        deployment_name = '', 
                        release_name = '', 
                        value = 1.337, 
                        workspace_id = '', )
                    ], 
                offset = 56, 
                total_deployments = 56
            )
        else :
            return InstantMetricsPaginated(
                limit = 56,
                metrics = [
                    astronomercoreapi.models.instant_metric.InstantMetric(
                        deployment_id = '', 
                        deployment_name = '', 
                        release_name = '', 
                        value = 1.337, 
                        workspace_id = '', )
                    ],
                offset = 56,
                total_deployments = 56,
        )
        """

    def testInstantMetricsPaginated(self):
        """Test InstantMetricsPaginated"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
