# coding: utf-8

"""
    Astro Core API

    Astro Core API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import astronomercoreapi
from astronomercoreapi.models.internal_mapped_task_instance_summary import InternalMappedTaskInstanceSummary  # noqa: E501
from astronomercoreapi.rest import ApiException

class TestInternalMappedTaskInstanceSummary(unittest.TestCase):
    """InternalMappedTaskInstanceSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InternalMappedTaskInstanceSummary
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalMappedTaskInstanceSummary`
        """
        model = astronomercoreapi.models.internal_mapped_task_instance_summary.InternalMappedTaskInstanceSummary()  # noqa: E501
        if include_optional :
            return InternalMappedTaskInstanceSummary(
                end_date = '', 
                overall_state = '', 
                start_date = '', 
                states = {
                    'key' : 56
                    }, 
                task_id = '', 
                try_number = 56
            )
        else :
            return InternalMappedTaskInstanceSummary(
        )
        """

    def testInternalMappedTaskInstanceSummary(self):
        """Test InternalMappedTaskInstanceSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
