# coding: utf-8

"""
    Astro Core API

    Astro Core API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import astronomercoreapi
from astronomercoreapi.models.internal_task import InternalTask  # noqa: E501
from astronomercoreapi.rest import ApiException

class TestInternalTask(unittest.TestCase):
    """InternalTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InternalTask
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalTask`
        """
        model = astronomercoreapi.models.internal_task.InternalTask()  # noqa: E501
        if include_optional :
            return InternalTask(
                extra_links = [
                    ''
                    ], 
                has_outlet_datasets = True, 
                id = '', 
                is_mapped = True, 
                label = '', 
                operator = '', 
                outlets = [
                    astronomercoreapi.models.internal_outlet.internal_Outlet(
                        extra = {
                            'key' : ''
                            }, 
                        type = '', 
                        uri = '', )
                    ]
            )
        else :
            return InternalTask(
        )
        """

    def testInternalTask(self):
        """Test InternalTask"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
