# coding: utf-8

"""
    Astro Core API

    Astro Core API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import astronomercoreapi
from astronomercoreapi.api.user_api import UserApi  # noqa: E501
from astronomercoreapi.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = astronomercoreapi.api.user_api.UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_org_user(self):
        """Test case for delete_org_user

        Remove user from organization  # noqa: E501
        """
        pass

    def test_delete_workspace_user(self):
        """Test case for delete_workspace_user

        Remove user from workspace  # noqa: E501
        """
        pass

    def test_get_self_user(self):
        """Test case for get_self_user

        Get self user information  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        Get user information  # noqa: E501
        """
        pass

    def test_list_org_users(self):
        """Test case for list_org_users

        List users in an organization  # noqa: E501
        """
        pass

    def test_list_workspace_users(self):
        """Test case for list_workspace_users

        List users in a workspace  # noqa: E501
        """
        pass

    def test_mutate_org_user_role(self):
        """Test case for mutate_org_user_role

        Mutate an organization role for user  # noqa: E501
        """
        pass

    def test_mutate_workspace_user_role(self):
        """Test case for mutate_workspace_user_role

        Mutate a workspace role for user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
