# coding: utf-8

"""
    Astro Core API

    Astro Core API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import astronomercoreapi
from astronomercoreapi.api.team_api import TeamApi  # noqa: E501
from astronomercoreapi.rest import ApiException


class TestTeamApi(unittest.TestCase):
    """TeamApi unit test stubs"""

    def setUp(self):
        self.api = astronomercoreapi.api.team_api.TeamApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_team_members(self):
        """Test case for add_team_members

        Add members to a team  # noqa: E501
        """
        pass

    def test_create_team(self):
        """Test case for create_team

        Create team  # noqa: E501
        """
        pass

    def test_delete_team(self):
        """Test case for delete_team

        Delete team  # noqa: E501
        """
        pass

    def test_delete_workspace_team(self):
        """Test case for delete_workspace_team

        Remove team from a workspace  # noqa: E501
        """
        pass

    def test_get_team(self):
        """Test case for get_team

        Get team  # noqa: E501
        """
        pass

    def test_list_organization_teams(self):
        """Test case for list_organization_teams

        List teams in an organization  # noqa: E501
        """
        pass

    def test_list_workspace_teams(self):
        """Test case for list_workspace_teams

        List teams in a workspace  # noqa: E501
        """
        pass

    def test_mutate_org_team_role(self):
        """Test case for mutate_org_team_role

        Mutate an organization role for team  # noqa: E501
        """
        pass

    def test_mutate_workspace_team_role(self):
        """Test case for mutate_workspace_team_role

        Mutate a workspace role for a team  # noqa: E501
        """
        pass

    def test_remove_team_member(self):
        """Test case for remove_team_member

        Remove member from a team  # noqa: E501
        """
        pass

    def test_update_team(self):
        """Test case for update_team

        Update team  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
