# coding: utf-8

"""
    Astro Core API

    Astro Core API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Dict, Optional
from pydantic import BaseModel, StrictStr

class InternalOutlet(BaseModel):
    """
    InternalOutlet
    """
    extra: Optional[Dict[str, StrictStr]] = None
    type: Optional[StrictStr] = None
    uri: Optional[StrictStr] = None
    __properties = ["extra", "type", "uri"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> InternalOutlet:
        """Create an instance of InternalOutlet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> InternalOutlet:
        """Create an instance of InternalOutlet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return InternalOutlet.parse_obj(obj)

        _obj = InternalOutlet.parse_obj({
            "extra": obj.get("extra"),
            "type": obj.get("type"),
            "uri": obj.get("uri")
        })
        return _obj

