# coding: utf-8

"""
    Astro Core API

    Astro Core API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, StrictBool, StrictInt, conlist
from astronomer_core_api.sdk.models.project_git_branch import ProjectGitBranch


class ProjectGitBranchesPaginated(BaseModel):
    """
    ProjectGitBranchesPaginated
    """

    branches: conlist(ProjectGitBranch) = Field(...)
    has_next_page: StrictBool = Field(..., alias="hasNextPage")
    page: StrictInt = Field(...)
    per_page: StrictInt = Field(..., alias="perPage")
    __properties = ["branches", "hasNextPage", "page", "perPage"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ProjectGitBranchesPaginated:
        """Create an instance of ProjectGitBranchesPaginated from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in branches (list)
        _items = []
        if self.branches:
            for _item in self.branches:
                if _item:
                    _items.append(_item.to_dict())
            _dict["branches"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ProjectGitBranchesPaginated:
        """Create an instance of ProjectGitBranchesPaginated from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ProjectGitBranchesPaginated.parse_obj(obj)

        _obj = ProjectGitBranchesPaginated.parse_obj(
            {
                "branches": [
                    ProjectGitBranch.from_dict(_item) for _item in obj.get("branches")
                ]
                if obj.get("branches") is not None
                else None,
                "has_next_page": obj.get("hasNextPage"),
                "page": obj.get("page"),
                "per_page": obj.get("perPage"),
            }
        )
        return _obj
