# coding: utf-8

"""
    Astro Core API

    Astro Core API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from pydantic import BaseModel, Field, StrictStr
from astronomer_core_api.sdk.models.machine_spec import MachineSpec


class SchedulerMachine(BaseModel):
    """
    SchedulerMachine
    """

    name: StrictStr = Field(..., description="The name of this machine.")
    spec: MachineSpec = Field(...)
    __properties = ["name", "spec"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SchedulerMachine:
        """Create an instance of SchedulerMachine from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of spec
        if self.spec:
            _dict["spec"] = self.spec.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SchedulerMachine:
        """Create an instance of SchedulerMachine from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SchedulerMachine.parse_obj(obj)

        _obj = SchedulerMachine.parse_obj(
            {
                "name": obj.get("name"),
                "spec": MachineSpec.from_dict(obj.get("spec"))
                if obj.get("spec") is not None
                else None,
            }
        )
        return _obj
