# coding: utf-8

"""
    Astro Core API

    Astro Core API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class WorkspaceDagRun(BaseModel):
    """
    WorkspaceDagRun
    """
    data_interval_end: Optional[StrictStr] = Field(None, alias="dataIntervalEnd")
    data_interval_start: Optional[StrictStr] = Field(None, alias="dataIntervalStart")
    end_date: Optional[StrictStr] = Field(None, alias="endDate")
    logical_date: Optional[StrictStr] = Field(None, alias="logicalDate")
    run_id: Optional[StrictStr] = Field(None, alias="runId")
    run_type: Optional[StrictStr] = Field(None, alias="runType")
    start_date: Optional[StrictStr] = Field(None, alias="startDate")
    state: Optional[StrictStr] = None
    __properties = ["dataIntervalEnd", "dataIntervalStart", "endDate", "logicalDate", "runId", "runType", "startDate", "state"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> WorkspaceDagRun:
        """Create an instance of WorkspaceDagRun from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> WorkspaceDagRun:
        """Create an instance of WorkspaceDagRun from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return WorkspaceDagRun.parse_obj(obj)

        _obj = WorkspaceDagRun.parse_obj({
            "data_interval_end": obj.get("dataIntervalEnd"),
            "data_interval_start": obj.get("dataIntervalStart"),
            "end_date": obj.get("endDate"),
            "logical_date": obj.get("logicalDate"),
            "run_id": obj.get("runId"),
            "run_type": obj.get("runType"),
            "start_date": obj.get("startDate"),
            "state": obj.get("state")
        })
        return _obj

