# coding: utf-8

"""
    Astro Registry API

    Astro Registry API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import astronomerregistry
from astronomerregistry.models.create_provider_request import CreateProviderRequest  # noqa: E501
from astronomerregistry.rest import ApiException

class TestCreateProviderRequest(unittest.TestCase):
    """CreateProviderRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateProviderRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateProviderRequest`
        """
        model = astronomerregistry.models.create_provider_request.CreateProviderRequest()  # noqa: E501
        if include_optional :
            return CreateProviderRequest(
                description = '', 
                display_name = '', 
                docs_url = '', 
                github_url = '', 
                is_certified = True, 
                is_cloud_ide_compatible = True, 
                is_display_name_manual = True, 
                is_featured = True, 
                is_global = True, 
                is_logo_manual = True, 
                is_private = True, 
                labels = [
                    ''
                    ], 
                logo = '', 
                name = '', 
                social_stats = astronomerregistry.models.social_stats.SocialStats(
                    stars = 56, 
                    views = 56, ), 
                type = 'Official', 
                version = ''
            )
        else :
            return CreateProviderRequest(
                name = '',
                type = 'Official',
                version = '',
        )
        """

    def testCreateProviderRequest(self):
        """Test CreateProviderRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
