# coding: utf-8

"""
    Astro Registry API

    Astro Registry API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import astronomerregistry
from astronomerregistry.models.update_label_request import UpdateLabelRequest  # noqa: E501
from astronomerregistry.rest import ApiException

class TestUpdateLabelRequest(unittest.TestCase):
    """UpdateLabelRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UpdateLabelRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateLabelRequest`
        """
        model = astronomerregistry.models.update_label_request.UpdateLabelRequest()  # noqa: E501
        if include_optional :
            return UpdateLabelRequest(
                description = '', 
                graphics = astronomerregistry.models.label_graphics.LabelGraphics(
                    banner = '', 
                    icon = '', ), 
                is_private = True
            )
        else :
            return UpdateLabelRequest(
        )
        """

    def testUpdateLabelRequest(self):
        """Test UpdateLabelRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
