# coding: utf-8

"""
    Astro Registry API

    Astro Registry API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import astronomerregistry
from astronomerregistry.models.create_module_request import CreateModuleRequest  # noqa: E501
from astronomerregistry.rest import ApiException

class TestCreateModuleRequest(unittest.TestCase):
    """CreateModuleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateModuleRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateModuleRequest`
        """
        model = astronomerregistry.models.create_module_request.CreateModuleRequest()  # noqa: E501
        if include_optional :
            return CreateModuleRequest(
                description = '', 
                display_name = '', 
                documentation = '', 
                github_url = '', 
                import_path = '', 
                inherits_from = astronomerregistry.models.module_inherits_from.ModuleInheritsFrom(
                    module_name = '', 
                    organization_id = '', 
                    provider_name = '', 
                    version = '', ), 
                is_certified = True, 
                is_cloud_ide_compatible = True, 
                is_display_name_manual = True, 
                is_featured = True, 
                is_global = True, 
                is_logo_manual = True, 
                is_private = True, 
                labels = [
                    ''
                    ], 
                logo = '', 
                name = '', 
                parameters = [
                    astronomerregistry.models.create_module_parameter_request.CreateModuleParameterRequest(
                        default_value = '', 
                        description = '', 
                        name = '', 
                        required = True, 
                        type = '', 
                        type_def = astronomerregistry.models.type_def.TypeDef(
                            annotation_type = '', 
                            raw_annotation = '', 
                            type_variables = [
                                astronomerregistry.models.type_def.TypeDef(
                                    annotation_type = '', 
                                    raw_annotation = '', )
                                ], ), )
                    ], 
                social_stats = astronomerregistry.models.social_stats.SocialStats(
                    stars = 56, 
                    views = 56, ), 
                type = 'Decorators'
            )
        else :
            return CreateModuleRequest(
                name = '',
                type = 'Decorators',
        )
        """

    def testCreateModuleRequest(self):
        """Test CreateModuleRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
