# coding: utf-8

"""
    Astro Registry API

    Astro Registry API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import astronomerregistry
from astronomerregistry.models.create_label_request import CreateLabelRequest  # noqa: E501
from astronomerregistry.rest import ApiException

class TestCreateLabelRequest(unittest.TestCase):
    """CreateLabelRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateLabelRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateLabelRequest`
        """
        model = astronomerregistry.models.create_label_request.CreateLabelRequest()  # noqa: E501
        if include_optional :
            return CreateLabelRequest(
                description = '', 
                graphics = astronomerregistry.models.label_graphics.LabelGraphics(
                    banner = '', 
                    icon = '', ), 
                is_private = True, 
                name = ''
            )
        else :
            return CreateLabelRequest(
                name = '',
        )
        """

    def testCreateLabelRequest(self):
        """Test CreateLabelRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
