# coding: utf-8

"""
    Astro Core API

    Astro Core API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, StrictStr, conlist
from astronomercoreapi.models.cell_run_task import CellRunTask

class CellRun(BaseModel):
    """
    CellRun
    """
    default_task_id: StrictStr = Field(..., alias="defaultTaskId")
    state: StrictStr = Field(...)
    tasks: conlist(CellRunTask) = Field(...)
    __properties = ["defaultTaskId", "state", "tasks"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CellRun:
        """Create an instance of CellRun from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in tasks (list)
        _items = []
        if self.tasks:
            for _item in self.tasks:
                if _item:
                    _items.append(_item.to_dict())
            _dict['tasks'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CellRun:
        """Create an instance of CellRun from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CellRun.parse_obj(obj)

        _obj = CellRun.parse_obj({
            "default_task_id": obj.get("defaultTaskId"),
            "state": obj.get("state"),
            "tasks": [CellRunTask.from_dict(_item) for _item in obj.get("tasks")] if obj.get("tasks") is not None else None
        })
        return _obj

