# coding: utf-8

"""
    Astro Core API

    Astro Core API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field
from astronomercoreapi.models.internal_mapped_task_instance_summary import InternalMappedTaskInstanceSummary
from astronomercoreapi.models.internal_unmapped_task_instance import InternalUnmappedTaskInstance

class InternalTaskInstancesInner(BaseModel):
    """
    InternalTaskInstancesInner
    """
    mapped_task_instance_summary: Optional[InternalMappedTaskInstanceSummary] = Field(None, alias="mappedTaskInstanceSummary")
    unmapped_task_instance: Optional[InternalUnmappedTaskInstance] = Field(None, alias="unmappedTaskInstance")
    __properties = ["mappedTaskInstanceSummary", "unmappedTaskInstance"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> InternalTaskInstancesInner:
        """Create an instance of InternalTaskInstancesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of mapped_task_instance_summary
        if self.mapped_task_instance_summary:
            _dict['mappedTaskInstanceSummary'] = self.mapped_task_instance_summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of unmapped_task_instance
        if self.unmapped_task_instance:
            _dict['unmappedTaskInstance'] = self.unmapped_task_instance.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> InternalTaskInstancesInner:
        """Create an instance of InternalTaskInstancesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return InternalTaskInstancesInner.parse_obj(obj)

        _obj = InternalTaskInstancesInner.parse_obj({
            "mapped_task_instance_summary": InternalMappedTaskInstanceSummary.from_dict(obj.get("mappedTaskInstanceSummary")) if obj.get("mappedTaskInstanceSummary") is not None else None,
            "unmapped_task_instance": InternalUnmappedTaskInstance.from_dict(obj.get("unmappedTaskInstance")) if obj.get("unmappedTaskInstance") is not None else None
        })
        return _obj

