# coding: utf-8

"""
    Astro Core API

    Astro Core API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, StrictStr, conlist
from astronomercoreapi.models.cluster_tag import ClusterTag
from astronomercoreapi.models.update_node_pool_request import UpdateNodePoolRequest

class UpdateGcpClusterRequest(BaseModel):
    """
    UpdateGcpClusterRequest
    """
    db_instance_type: StrictStr = Field(..., alias="dbInstanceType")
    k8s_tags: conlist(ClusterTag) = Field(..., alias="k8sTags")
    name: StrictStr = Field(...)
    node_pools: conlist(UpdateNodePoolRequest) = Field(..., alias="nodePools")
    template_version: StrictStr = Field(..., alias="templateVersion")
    __properties = ["dbInstanceType", "k8sTags", "name", "nodePools", "templateVersion"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UpdateGcpClusterRequest:
        """Create an instance of UpdateGcpClusterRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in k8s_tags (list)
        _items = []
        if self.k8s_tags:
            for _item in self.k8s_tags:
                if _item:
                    _items.append(_item.to_dict())
            _dict['k8sTags'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in node_pools (list)
        _items = []
        if self.node_pools:
            for _item in self.node_pools:
                if _item:
                    _items.append(_item.to_dict())
            _dict['nodePools'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UpdateGcpClusterRequest:
        """Create an instance of UpdateGcpClusterRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UpdateGcpClusterRequest.parse_obj(obj)

        _obj = UpdateGcpClusterRequest.parse_obj({
            "db_instance_type": obj.get("dbInstanceType"),
            "k8s_tags": [ClusterTag.from_dict(_item) for _item in obj.get("k8sTags")] if obj.get("k8sTags") is not None else None,
            "name": obj.get("name"),
            "node_pools": [UpdateNodePoolRequest.from_dict(_item) for _item in obj.get("nodePools")] if obj.get("nodePools") is not None else None,
            "template_version": obj.get("templateVersion")
        })
        return _obj

