# coding: utf-8

"""
    Astro Registry API

    Astro Registry API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import astronomerregistry
from astronomerregistry.models.providers_paginated import ProvidersPaginated  # noqa: E501
from astronomerregistry.rest import ApiException

class TestProvidersPaginated(unittest.TestCase):
    """ProvidersPaginated unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ProvidersPaginated
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProvidersPaginated`
        """
        model = astronomerregistry.models.providers_paginated.ProvidersPaginated()  # noqa: E501
        if include_optional :
            return ProvidersPaginated(
                filters = astronomerregistry.models.provider_filters.ProviderFilters(
                    badges = [
                        astronomerregistry.models.short_label.ShortLabel(
                            description = '', 
                            id = '', 
                            name = '', )
                        ], 
                    categories = [
                        astronomerregistry.models.short_label.ShortLabel(
                            description = '', 
                            id = '', 
                            name = '', )
                        ], 
                    tiers = [
                        
                        ], ), 
                limit = 56, 
                offset = 56, 
                providers = [
                    astronomerregistry.models.provider.Provider(
                        badges = [
                            astronomerregistry.models.short_label.ShortLabel(
                                description = '', 
                                id = '', 
                                name = '', )
                            ], 
                        categories = [
                            astronomerregistry.models.short_label.ShortLabel(
                                description = '', 
                                id = '', 
                                name = '', )
                            ], 
                        created_at = '', 
                        created_by = '', 
                        description = '', 
                        display_name = '', 
                        docs_url = '', 
                        github_url = '', 
                        is_certified = True, 
                        is_cloud_ide_compatible = True, 
                        is_display_name_manual = True, 
                        is_featured = True, 
                        is_global = True, 
                        is_latest_version = True, 
                        is_logo_manual = True, 
                        is_private = True, 
                        logo = '', 
                        name = '', 
                        organization_id = '', 
                        other_versions = [
                            ''
                            ], 
                        provider_id = '', 
                        search_rank = 56, 
                        short_name_id = '', 
                        social_stats = astronomerregistry.models.social_stats.SocialStats(
                            stars = 56, 
                            views = 56, ), 
                        tiers = [
                            
                            ], 
                        type = '', 
                        updated_at = '', 
                        updated_by = '', 
                        version = '', )
                    ], 
                total_count = 56
            )
        else :
            return ProvidersPaginated(
                filters = astronomerregistry.models.provider_filters.ProviderFilters(
                    badges = [
                        astronomerregistry.models.short_label.ShortLabel(
                            description = '', 
                            id = '', 
                            name = '', )
                        ], 
                    categories = [
                        astronomerregistry.models.short_label.ShortLabel(
                            description = '', 
                            id = '', 
                            name = '', )
                        ], 
                    tiers = [
                        
                        ], ),
                limit = 56,
                offset = 56,
                providers = [
                    astronomerregistry.models.provider.Provider(
                        badges = [
                            astronomerregistry.models.short_label.ShortLabel(
                                description = '', 
                                id = '', 
                                name = '', )
                            ], 
                        categories = [
                            astronomerregistry.models.short_label.ShortLabel(
                                description = '', 
                                id = '', 
                                name = '', )
                            ], 
                        created_at = '', 
                        created_by = '', 
                        description = '', 
                        display_name = '', 
                        docs_url = '', 
                        github_url = '', 
                        is_certified = True, 
                        is_cloud_ide_compatible = True, 
                        is_display_name_manual = True, 
                        is_featured = True, 
                        is_global = True, 
                        is_latest_version = True, 
                        is_logo_manual = True, 
                        is_private = True, 
                        logo = '', 
                        name = '', 
                        organization_id = '', 
                        other_versions = [
                            ''
                            ], 
                        provider_id = '', 
                        search_rank = 56, 
                        short_name_id = '', 
                        social_stats = astronomerregistry.models.social_stats.SocialStats(
                            stars = 56, 
                            views = 56, ), 
                        tiers = [
                            
                            ], 
                        type = '', 
                        updated_at = '', 
                        updated_by = '', 
                        version = '', )
                    ],
                total_count = 56,
        )
        """

    def testProvidersPaginated(self):
        """Test ProvidersPaginated"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
