# coding: utf-8

"""
    Astro Registry API

    Astro Registry API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import astronomerregistry
from astronomerregistry.api.dag_api import DagApi  # noqa: E501
from astronomerregistry.rest import ApiException


class TestDagApi(unittest.TestCase):
    """DagApi unit test stubs"""

    def setUp(self):
        self.api = astronomerregistry.api.dag_api.DagApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_dag(self):
        """Test case for create_dag

        Create dag for registry  # noqa: E501
        """
        pass

    def test_delete_dag(self):
        """Test case for delete_dag

        Delete a dag  # noqa: E501
        """
        pass

    def test_get_dag(self):
        """Test case for get_dag

        Get dag  # noqa: E501
        """
        pass

    def test_list_dags(self):
        """Test case for list_dags

        List dags  # noqa: E501
        """
        pass

    def test_update_dag(self):
        """Test case for update_dag

        Update dag for registry  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
