# coding: utf-8

"""
    Astro Registry API

    Astro Registry API  # noqa: E501

    The version of the OpenAPI document: v1alpha1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import astronomerregistry
from astronomerregistry.models.update_module_parameter_request import UpdateModuleParameterRequest  # noqa: E501
from astronomerregistry.rest import ApiException

class TestUpdateModuleParameterRequest(unittest.TestCase):
    """UpdateModuleParameterRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UpdateModuleParameterRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateModuleParameterRequest`
        """
        model = astronomerregistry.models.update_module_parameter_request.UpdateModuleParameterRequest()  # noqa: E501
        if include_optional :
            return UpdateModuleParameterRequest(
                default_value = '', 
                description = '', 
                name = '', 
                required = True, 
                type = '', 
                type_def = astronomerregistry.models.type_def.TypeDef(
                    annotation_type = '', 
                    raw_annotation = '', 
                    type_variables = [
                        astronomerregistry.models.type_def.TypeDef(
                            annotation_type = '', 
                            raw_annotation = '', )
                        ], )
            )
        else :
            return UpdateModuleParameterRequest(
                name = '',
                required = True,
        )
        """

    def testUpdateModuleParameterRequest(self):
        """Test UpdateModuleParameterRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
